#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Test-AtRuntime
version:      0.01
version_from: lib/Test/AtRuntime.pm
installdirs:  site
requires:
    Test::Harness:                 2.01
    Test::Builder:                 0.17
    File::Spec:                    0.8
    Filter::Simple:                0.77
    Regexp::Common:                2.11

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
